<?php

/**
 * @file
 * Delete config while uninstall a module.
 */

/**
 * Implements hook_uninstall().
 */
function product_migrate_uninstall() {
  $configs = [
    'migrate_plus.migration_group.product_migrate',
    'migrate_plus.migration.product_migration',
  ];

  foreach ($configs as $config) {
    $delete = \Drupal::database()->delete('config')
      ->condition('name', $config)
      ->execute();
  }
  drupal_flush_all_caches();
}
